version: '1'

services:
  reverse-proxy:
    image: nginx:latest
    container_name: reverse_proxy
    depends_on:
      - weather-app
      - weather-report
      - precipitation-service
    volumes:
      - ./nginx-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

  weather-app:
    image: weather-app
    container_name: weather-app
    build:
      context: ./weather-app
    depends_on:
      - weather-report
      - precipitation-service
    ports:
      - "3000:80"
    restart: on-failure

  weather-report:
    image: weather-report
    container_name: weather-report
    build:
        context: ./weatherreport
    ports:
      - "8082:8082"

  precipitation-service:
    image: precipitation-service
    container_name: precipitation-service
    build:
        context: ./precipitation
    ports:
      - "8081:8081"